name: Facebook to Discord

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore lastPostId from cache
        uses: actions/cache@v3
        with:
          path: .cache/fb.json
          key: fb-last-post-id
          restore-keys: fb-last-post-id

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Save updated post ID to cache
        uses: actions/cache@v3
        with:
          path: .cache/fb.json
          key: fb-last-post-id-${{ github.run_id }} # Unique key to save new cache
          restore-keys: fb-last-post-id
